/*
 * RSA Digital Signature Verification for ESP32
 * Verifies RSA-SHA256 signatures for firmware authenticity
 */

#ifndef RSA_VERIFY_H
#define RSA_VERIFY_H

#include <Arduino.h>
#include <mbedtls/pk.h>
#include <mbedtls/md.h>
#include <mbedtls/sha256.h>

// RSA public key (will be generated by sign_firmware.py)
// This is a placeholder - will be replaced with actual key
extern const unsigned char rsa_public_key[];
extern const size_t rsa_public_key_len;

/**
 * Verify RSA-SHA256 signature of firmware
 * @param firmware_data Pointer to firmware data
 * @param firmware_len Length of firmware data
 * @param signature_data Pointer to signature data
 * @param signature_len Length of signature data
 * @return true if signature is valid, false otherwise
 */
bool rsa_verify_firmware(const uint8_t* firmware_data, size_t firmware_len,
                        const uint8_t* signature_data, size_t signature_len);

/**
 * Download and verify firmware signature from URL
 * @param firmware_url URL to firmware file
 * @param signature_url URL to signature file
 * @return true if signature is valid, false otherwise
 */
bool rsa_verify_firmware_from_url(const char* firmware_url, const char* signature_url);

/**
 * Initialize RSA verification context
 * @return true if initialization successful, false otherwise
 */
bool rsa_verify_init();

/**
 * Cleanup RSA verification context
 */
void rsa_verify_cleanup();

#endif // RSA_VERIFY_H
